services:
  cmsqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: cmsqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - companymanagement

  cm-api:
    build:
      context: ./CompanyManagementAPI
      dockerfile: Dockerfile
    container_name: cm-api
    depends_on:
      - cmsqlserver
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=cmsqlserver;Database=companydb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True; 
    networks:
      - companymanagement

volumes:
  sql_data:

networks:
  companymanagement:
    driver: bridge
